org: hutechuniversity
app: transactionchatbot
service: backend

provider:
    name: aws
    runtime: python3.8
    region: us-east-1

plugins:
    - serverless-offline
    - serverless-python-requirements

custom:
    pythonRequirements:
        dockerizePip: non-linux
        zip: true
        exclude:
            - venv/**
            - tests/**

package:
    exclude:
        - venv/**
        - node_modules/**

functions:
    extractAndStoreText:
        handler: handler.extract_and_store
        timeout: 30
        events:
            - http:
                  path: extract
                  method: post
                  cors: true

resources:
    Resources:
        ChatbotDynamoDB:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: UserInputTable
                AttributeDefinitions:
                    - AttributeName: timestamp
                      AttributeType: S
                KeySchema:
                    - AttributeName: timestamp
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 5
                    WriteCapacityUnits: 5
